# Generated by Django 5.2.1 on 2025-05-18 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbackapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='keywords',
            field=models.TextField(blank=True),
        ),
    ]
