# Generated by Django 5.2.1 on 2025-05-18 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbackapi', '0002_feedback_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='emotion',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
