# Generated by Django 5.2.1 on 2025-05-19 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbackapi', '0003_feedback_emotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='aspect_sentiments',
            field=models.JSONField(default=dict),
        ),
    ]
